environment:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
packages:
  - name: sample
    actions:
      - name: sms
        package: sample
        runtime: 'python:default'