alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: 0x213F/serverless-sounds-radiant-2
  name: sms-api
  routes:
  - path: /
  source_dir: /
name: sms
